ASP.NET MVC/Notes Homework 11.1/Notes Homework 11.1/Notes Homework 11.1/Models/ErrorViewModel.cs
namespace Notes_Homework_11._1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP.NET MVC/Notes Homework 11.1/Notes Homework 11.1/Notes Homework 11.1/Models/Note.cs
using System.ComponentModel.DataAnnotations;

namespace Notes_Homework_11._1.Models
{
    public class Note
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Note Title")]
        public string? Title { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Text")]
        public string? Text { get; set; }

        [Required]
        [Display(Name = "Creation Date")]
        public DateTime CreatedAt { get; set; }

        [Display(Name = "Tags")]
        public string? Tags { get; set; }
    }
}

ASP.NET MVC/Notes Homework 11.1/Notes Homework 11.1/Notes Homework 11.1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Notes_Homework_11._1.Models;
using System.Diagnostics;

namespace Notes_Homework_11._1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET MVC/Notes Homework 11.1/Notes Homework 11.1/Notes Homework 11.1/Controllers/NoteController.cs
using Notes_Homework_11._1.Data;
using Notes_Homework_11._1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Notes_Homework_11._1.Controllers
{
    public class NoteController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NoteController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<Note> notes = _context.Notes;

            return View(notes); 
        }
        public  IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Note note)
        {
            if (ModelState.IsValid)
            {
                _context.Notes.Add(note);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(note);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var note = _context.Notes.Find(id);

            if (note == null)
            {
                return NotFound();
            }
            return View(note);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Note note)
        {
            if (ModelState.IsValid)
            {
                _context.Notes.Update(note);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(note);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var note = _context.Notes.Find(id);

            if (note == null)
            {
                return NotFound();
            }
            return View(note);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult DeleteNote(int? id)
        {
            var note = _context.Notes.Find(id);
            if (note == null)
            {
                return NotFound();
            }
            _context.Notes.Remove(note);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ASP.NET MVC/Notes Homework 11.1/Notes Homework 11.1/Notes Homework 11.1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Use Notes</h1>
</div>

ASP.NET MVC/Notes Homework 11.1/Notes Homework 11.1/Notes Homework 11.1/Views/Note/Create.cshtml
@model Note

<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Create New Note</h2>
    </div>

    <form method="post">
        <div asp-validation-summary="All" class="alert alert-danger"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Title">Note Title</label>
                <input type="text" class="form-control mb-3" asp-for="Title" placeholder="Enter Note Title" required>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="CreatedAt">Created At</label>
                <input type="datetime-local" class="form-control mb-3" asp-for="CreatedAt" required>
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-12">
                <label asp-for="Text">Note Content</label>
                <textarea class="form-control mb-3" asp-for="Text" placeholder="Enter Note Content" rows="5" required></textarea>
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-12">
                <label asp-for="Tags">Tags</label>
                <input type="text" class="form-control mb-3" asp-for="Tags" placeholder="Enter Tags (comma separated)">
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i> Save</button>
        <a asp-controller="Note" asp-action="Index" class="btn btn-lg btn-warning p-2">Back to List</a>
    </form>
</div>

@section Scripts {
    @{ 
                <partial name="_ValidationScriptsPartial" />
    }
}

ASP.NET MVC/Notes Homework 11.1/Notes Homework 11.1/Notes Homework 11.1/Views/Note/Delete.cshtml
@model Note

<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Delete Note</h2>
    </div>

    <form method="post" asp-action="DeleteNote">
        <input asp-for="Id" hidden />
        <div asp-validation-summary="All" class="alert alert-danger"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Title">Note Title</label>
                <input type="text" class="form-control mb-3" asp-for="Title" placeholder="Enter Note Title" disabled>
                <span asp-validation-for="Title" class="alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="CreatedAt">Created At</label>
                <input type="datetime-local" class="form-control mb-3" asp-for="CreatedAt" disabled>
                <span asp-validation-for="CreatedAt" class="alert-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-12">
                <label asp-for="Text">Note Content</label>
                <textarea class="form-control mb-3" asp-for="Text" placeholder="Enter Note Content" rows="5" disabled></textarea>
                <span asp-validation-for="Text" class="alert-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-12">
                <label asp-for="Tags">Tags</label>
                <input type="text" class="form-control mb-3" asp-for="Tags" placeholder="Enter Tags" disabled>
                <span asp-validation-for="Tags" class="alert-danger"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-lg btn-danger p-2"><i class="bi bi-trash-fill"></i> Delete</button>
        <a asp-controller="Note" asp-action="Index" class="btn btn-lg btn-warning p-2">Back to List</a>
    </form>

</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

ASP.NET MVC/Notes Homework 11.1/Notes Homework 11.1/Notes Homework 11.1/Views/Note/Edit.cshtml
@model Note

<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Edit Note</h2>
    </div>

    <form method="post" asp-action="Edit">
        <div asp-validation-summary="All" class="alert alert-danger"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Title">Note Title</label>
                <input type="text" class="form-control mb-3" asp-for="Title" placeholder="Enter Note Title" required>
                <span asp-validation-for="Title" class="alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="CreatedAt">Created At</label>
                <input type="datetime-local" class="form-control mb-3" asp-for="CreatedAt" required>
                <span asp-validation-for="CreatedAt" class="alert-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-12">
                <label asp-for="Text">Note Content</label>
                <textarea class="form-control mb-3" asp-for="Text" placeholder="Enter Note Content" rows="5" required></textarea>
                <span asp-validation-for="Text" class="alert-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-12">
                <label asp-for="Tags">Tags</label>
                <input type="text" class="form-control mb-3" asp-for="Tags" placeholder="Enter Tags (comma separated)">
                <span asp-validation-for="Tags" class="alert-danger"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i> Update</button>
        <a asp-controller="Note" asp-action="Index" class="btn btn-lg btn-warning p-2">Back to List</a>
    </form>

</div>

@* Front end validation *@
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ASP.NET MVC/Notes Homework 11.1/Notes Homework 11.1/Notes Homework 11.1/Views/Note/Index.cshtml
@model IEnumerable<Note>

@{
    ViewData["Title"] = "Note List";
}

<div class="container shadow p-5">
    <h1>Note CRUD Demo</h1>

    <div class="col mb-3">
        <a asp-controller="Note" asp-action="Create" class="btn btn-lg btn-primary"><i class="bi bi-file-plus-fill"></i> Add Note</a>
    </div>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Text</th>
                <th scope="col">Created At</th>
                <th scope="col">Tags</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var note in Model)
            {
                    <tr>
                        <td>@note.Title</td>
                        <td>@note.Text</td>
                        <td>@note.CreatedAt</td>
                        <td>@note.Tags</td>
                        <td>
                            <div role="group" class="w-60 btn-group">
                                <span style="margin-right: 5px;">
                                    <a asp-controller="Note" asp-action="Edit" asp-route-id="@note.Id" class="btn btn-sm btn-primary"><i class="bi bi-pencil-square"></i> Edit</a>
                                </span>
                                <span>
                                    <a asp-controller="Note" asp-action="Delete" asp-route-id="@note.Id" class="btn btn-sm btn-danger"><i class="bi bi-trash-fill"></i> Delete</a>
                                </span>
                            </div>
                        </td>
                    </tr>
            }
        </tbody>
    </table>
</div>

ASP.NET MVC/Notes Homework 11.1/Notes Homework 11.1/Notes Homework 11.1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Notes_Homework_11._1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Notes_Homework_11._1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Notes_Homework_11._1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="Index">All Notes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="Create">Create Note</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Notes_Homework_11._1 - 
        <a asp-area="" asp-controller="Home" asp-action="Index">Home</a> |
        <a asp-area="" asp-controller="Note" asp-action="Index">All Notes</a> |
        <a asp-area="" asp-controller="Note" asp-action="Create">Create Note</a> |
        <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>